### ISSUE TITLE
Fishes are designated as weapons

### ISSUE THREAD

**Issue by orbittwz** [Jaxe-Dev/MoreFilters#2]
Hey!
after some tinkering by another user, More Filters is designating fishes as neolithic weapons
![image](https://user-images.githubusercontent.com/45605734/163037024-2811ffc1-8c90-415b-b3f2-42581336e554.png)
I will try to understand why by myself later but can you take a look?
Thanks

**Comment by orbittwz** [comment]
yep just confirmed, I removed the mod from my list and the fishes are designated to the right place...

**Comment by orbittwz** [comment]
each fish is having these properties
```
		<techLevel>Neolithic</techLevel>
		<comps>
			<li>
				<compClass>CompEquippable</compClass>
			</li>
		</comps>
```
so it's clear that More Filters is not wrong designating those as a weapon
maybe that can be avoided somehow?

**Comment by Jaxe-Dev** [comment]
This may be better taken up with the fish mod
